"""
Centralize place for all string messages
"""

APP_TITLE = "Yify"
APP_DESCRIPTION = "A Yify website clone, where users can view, search, and filter movies;\
                    registered users can also add movies"

INVALID_EMAIL = "Invalid email address"
EMAIL_ALREADY_EXISTS = "User with this email address already exists"
ACCOUNT_CREATED_SUCCESS = "Account created successfully!"
USER_DOES_NOT_EXISTS = "User with this email does not exists"
INVALID_PASSWORD = "Invalid password, Please try again."
LOGIN_SUCCESS = "Logged in successfully!"
INVALID_TOKEN = "Invalid token or token is expired"
TOKEN_REFRESH_SUCCESS = "Token refreshed successfully"
AUTH_ERROR = "Authentication required"
PROFILE_DETAILS_SUCCESS = "Profile details"
PROFILE_DETAILS_UPDATED = "Profile details updated successfully"
INVALID_DATA_PASSED = "Invalid data passed"
PROFILE_DELETE_SUCCESS = "Profile deleted successfully"
PASSWORD_CONTAINS_SPACES = "Password should not contains any spaces"
PASSWORD_CONTAINS_NAME_EMAIL = ("Password should not contains either your "
                                "first name, last name or email address")
PASSWORD_CONTAINS_LOWER_CHARS = "Password should contain at least one upper case character"
PASSWORD_CONTAINS_UPPER_CHARS = "Password should contain at least one lower case character"
PASSWORD_DIGITS_ERROR = "Password should contain at least one digit"
PASSWORD_SPECIAL_CHAR_ERROR = "Password should contain at least one special character"
PASSWORD_LENGTH_ERROR = "Password should contains at least 8 characters"
PASSWORD_EMPTY_ERROR = "{} should not be empty."
PASSWORD_SAME_ERROR = "Old and new password should not be same."
OLD_PASSWORD_ERROR = "Old password is incorrect."
PASSWORD_UPDATE_SUCCESS = "Password updated successfully!"
RESET_PASSWORD_LINK_SUCCESS = "Reset password link send to your email address successfully!"
EMAIL_ERROR = "Error caught while sending email, Please try again later."
INVALID_RESET_PASSWORD_LINK = "Invalid reset password link or link is expired"
PASSWORD_NOT_MATCH = "New password and confirm password does not match"
MOVIE_ADDED_SUCCESSFULLY = "Movie details added successfully!"
MOVIE_DETAIL_ERROR = "Error while fetching movie details"
INVALID_YEAR_ERROR = "Invalid year value"
MOVIE_UPDATE_ERROR = "Error while updating movie details, Please check the request data"
PERMISSION_ERROR = "You cannot perform this action."
MOVIE_UPDATE_SUCCESS = "Movie details updated successfully!"
MOVIE_DELETE_ERROR = "Error while deleting movie"
MOVIE_DELETE_SUCCESS = "Movie deleted successfully!"
ADD_RATING_ERROR = "Error while adding a rating"
ADD_RATING_SUCCESS = "Rating added successfully!"
RATING_VALUE_ERROR = "Invalid rating value, Please value is between 0 and 10"
