"""
Centralize place for all string messages
"""

APP_TITLE = "Yify"
APP_DESCRIPTION = "A Yify website clone, where users can view, search, and filter movies;\
                    registered users can also add movies"

INVALID_EMAIL = "Invalid email address"
EMAIL_ALREADY_EXISTS = "User with this email address already exists"
ACCOUNT_CREATED_SUCCESS = "Account created successfully!"
USER_DOES_NOT_EXISTS = "User with this email does not exists"
INVALID_PASSWORD = "Invalid password, Please try again."
LOGIN_SUCCESS = "Logged in successfully!"
INVALID_TOKEN = "Invalid token or token is expired"
TOKEN_REFRESH_SUCCESS = "Token refreshed successfully"
AUTH_ERROR = "Authentication required"
PROFILE_DETAILS_SUCCESS = "Profile details"
PROFILE_DETAILS_UPDATED = "Profile details updated successfully"
INVALID_DATA_PASSED = "Invalid data passed"
PROFILE_DELETE_SUCCESS = "Profile deleted successfully"
PASSWORD_CONTAINS_SPACES = "Password should not contains any spaces"
PASSWORD_CONTAINS_NAME_EMAIL = ("Password should not contains either your "
                                "first name, last name or email address")
PASSWORD_CONTAINS_LOWER_CHARS = "Password should contain at least one upper case character"
PASSWORD_CONTAINS_UPPER_CHARS = "Password should contain at least one lower case character"
PASSWORD_DIGITS_ERROR = "Password should contain at least one digit"
PASSWORD_SPECIAL_CHAR_ERROR = "Password should contain at least one special character"
PASSWORD_LENGTH_ERROR = "Password should contains at least 8 characters"
PASSWORD_EMPTY_ERROR = "{} should not be empty."
PASSWORD_SAME_ERROR = "Old and new password should not be same."
OLD_PASSWORD_ERROR = "Old password is incorrect."
PASSWORD_UPDATE_SUCCESS = "Password updated successfully!"
